package com.cdqblog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("articletype", "id", Articletype.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("hotarticle", "id", Hotarticle.class);
		arp.addMapping("manager", "id", Manager.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("onedayword", "id", Onedayword.class);
		arp.addMapping("photo", "id", Photo.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("userip", "id", Userip.class);
	}
}

