package com.cdqblog.model;

import com.cdqblog.model.base.BaseArticletype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Articletype extends BaseArticletype<Articletype> {
	public static final Articletype dao = new Articletype().dao();
}
