package com.cdqblog.model;

import com.cdqblog.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {

	public static int TYPE_JAVAWEB=0;//0表示文章类型为java web
	public static int TYPE_JAVA=1;//1表示文章类型为java
	public static int TYPE_JFINAL=2;//2表示文章类型为jfinal
	public static int TYPE_MYSQL=3; //3表示文章类型为mysql

	public static final Article dao = new Article().dao();
}
