package com.cdqblog.model;

import com.cdqblog.model.base.BaseHotarticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hotarticle extends BaseHotarticle<Hotarticle> {
	public static final Hotarticle dao = new Hotarticle().dao();
}
