package com.cdqblog.model;

import com.cdqblog.model.base.BaseManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manager extends BaseManager<Manager> {
	public static int STATUS_NORMAL=0;
	public static int STATUS_LAHEI=-1;
	public static int ROLE_SUPERMANAGER=0;
	public static int ROLE_MANAGER=1;
	public static final Manager dao = new Manager().dao();
}
