package com.cdqblog.model;

import com.cdqblog.model.base.BaseOnedayword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Onedayword extends BaseOnedayword<Onedayword> {
	public static final Onedayword dao = new Onedayword().dao();
}
