package com.cdqblog.model;

import com.cdqblog.model.base.BaseUserip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userip extends BaseUserip<Userip> {
	public static final Userip dao = new Userip().dao();
}
