package com.cdqblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePhoto<M extends BasePhoto<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setWidth(java.lang.Integer width) {
		set("width", width);
		return (M)this;
	}
	
	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setHeight(java.lang.Long height) {
		set("height", height);
		return (M)this;
	}
	
	public java.lang.Long getHeight() {
		return getLong("height");
	}

	public M setDelete(java.lang.String delete) {
		set("delete", delete);
		return (M)this;
	}
	
	public java.lang.String getDelete() {
		return getStr("delete");
	}

	public M setFilename(java.lang.String filename) {
		set("filename", filename);
		return (M)this;
	}
	
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	public M setStorename(java.lang.String storename) {
		set("storename", storename);
		return (M)this;
	}
	
	public java.lang.String getStorename() {
		return getStr("storename");
	}

	public M setSize(java.lang.Integer size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Integer getSize() {
		return getInt("size");
	}

	public M setHash(java.lang.String hash) {
		set("hash", hash);
		return (M)this;
	}
	
	public java.lang.String getHash() {
		return getStr("hash");
	}

	public M setTimestamp(java.util.Date timestamp) {
		set("timestamp", timestamp);
		return (M)this;
	}
	
	public java.util.Date getTimestamp() {
		return get("timestamp");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
