package com.cdqblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticletype<M extends BaseArticletype<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreatedDate(java.util.Date createdDate) {
		set("createdDate", createdDate);
		return (M)this;
	}
	
	public java.util.Date getCreatedDate() {
		return get("createdDate");
	}

}
